### ISSUE TITLE
NameError: name 'load_lua' is not defined

### ISSUE THREAD

**Issue by pzq-xjtu** [OaDsis/DerainCycleGAN#1]
Thanks for your wonderful work. I ran train.py but I meet an error. NameError: name 'load_lua' is not defined. The version of torch is 1.7.1.

**Comment by pzq-xjtu** [comment]
There was another error when I  repalced load_lua with torchfile.load. 
struct.error: unpack requires a buffer of 4 bytes.

**Comment by OaDsis** [comment]
Sorry for that. We have modified the code (i.e., model.py and network.py). Please update them, and it should be working now.

**Comment by pzq-xjtu** [comment]
Thank you for your reply  quickly. Yes , it works now.

**Comment by mawei-north** [comment]
> 感谢您的出色工作。我跑 train.py 但遇到了错误。名称错误： 未定义名称“load_lua”。火炬的版本是 1.7.1。

Hello, I currently encountered the same problem while running this code. How did you resolve it at that time? Torch version 1.4.0
