### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by Mrhard1999** [OaDsis/DerainCycleGAN#11]
为什么下载了文件，依然会出现“NameError： name 'load_lua' is not defined”，load_lua在高版本pytorch中有可以替换的函数吗

**Comment by mawei-north** [comment]
You can download pre-trained vgg16-weight from here: https://drive.google.com/drive/folders/1DvOFGIdXXnNm1iage69HuasUPHZSXYYt.
And put it in "./vgg16/vgg16.weight", you will never face NameError again.

**Comment by OaDsis** [comment]
You can refer to the reply above, and thanks to mawei-north.
