### ISSUE TITLE
The input image size must be a multiple of 4?

### ISSUE THREAD

**Issue by Abandonist** [OaDsis/DerainCycleGAN#17]
Thank you for sharing such an excellent model and code. It has been very helpful to my project.

When testing my own dataset, I found that the test script does not work for some images, and the error message is as follows:
![error](https://github.com/OaDsis/DerainCycleGAN/assets/24521725/be37270a-9702-40cc-a810-66d91f7970c6)

After investigation, it was found that the width and height of the input image must be multiples of four, which may be caused by the model structure. So I added the following code after load_img to run it normally:
    width, height = img.size
    img = img.resize(((width // 4) * 4, (height // 4) * 4))

I don't have a sufficient understanding of its principle, and I'm not sure if this modification is correct. I hope it won't affect the performance of the model.

**Comment by OaDsis** [comment]
Thank you for your attention to our work. If you use your own data set, a resolution that cannot be completely divisible will cause the model to be unable to output results because the model uses multiple downsampling operations. If you run successfully by limiting the resolution, Then you can indeed do this.

**Comment by Abandonist** [comment]
Thank you for your reply. This has solved my problem.

**Comment by EXGHLI** [comment]
> load_img之後添加了以下程式碼以正常運行它：

Could you please tell me which file to modify?
Thank you very much!

**Comment by Abandonist** [comment]
> > load_img之後添加了以下程式碼以正常運行它：
> 
> Could you please tell me which file to modify? Thank you very much!

It should be in the dataset.py file, just resize the image after load_img
