### ISSUE TITLE
quantitative result

### ISSUE THREAD

**Issue by yzy-0001** [OaDsis/DerainCycleGAN#2]
Thank you for your article. I followed the guidance of readme, but the quantitative results could not reach that in the paper. At the current stage, I only tried rain100L. Can you provide your email? (I've tried your previous mailbox can't receive mail)  I really want to ask you about the problems I encounter. Thanks a lot.

**Comment by OaDsis** [comment]
Thanks for your attention. If you have any questions, please contact my email: weiyanyan@mail.hfut.edu.cn.
