### ISSUE TITLE
关于Table1中的SPANet-Dataset结果

### ISSUE THREAD

**Issue by 1180300419** [OaDsis/DerainCycleGAN#3]
![QQ图片20220830092530](https://user-images.githubusercontent.com/48647707/187327356-7a5f522e-4f11-4c97-81d5-e14b69aa48c7.png)
您好，请问Table1中SPANet-Dataset的结果是如何得到的呢？SPANet-Dataset数据集中的图片都是裁剪成256*256大小的patch,而不是一张完整的图片，您在使用的时候是每个epoch遍历所有的patch还是遍历所有的整张图片，随机挑选一个patch图片？我注意到所有的patch有63万多张，而整张的图片有2万多张。

**Comment by OaDsis** [comment]
你好，是遍历SPANet-Dataset中所有patch数据，我们没有整张图片的资源。

**Comment by 1180300419** [comment]
![image](https://user-images.githubusercontent.com/48647707/187434245-894065f6-3dd9-45aa-a56c-eabe377529a6.png)
您好，我又仔细地看了一下实验部分，论文的意思是：使用Rain100L进行训练，使用SPANet-Data进行吧。

**Comment by OaDsis** [comment]
是的
