### ISSUE TITLE
Missing GMM loss and LSTM 

### ISSUE THREAD

**Issue by Hello-Felix** [OaDsis/DerainCycleGAN#4]
Two questions please:
1）Why is there no GMM loss in the code ?
2）Why is there no LSTM in U-ARSE ?

**Comment by OaDsis** [comment]
Thanks for your attention.
1) We remove the GMM loss in the TIP publication version, please refer to https://ieeexplore.ieee.org/abstract/document/9420312.
2) The LSTM mechanism is applied in URAD of networks.py.
