### ISSUE TITLE
关于一些代码问题

### ISSUE THREAD

**Issue by jjb202** [OaDsis/DerainCycleGAN#5]
在saver.py文件中保存图像torchvision.utils.save_image(assembled_images1 / 2+0.5,) 这个assembled_images1为什么要除2加0.5呢？是因为assembled_images1张量里面有负数？变换成正的还是因为啥？

**Comment by OaDsis** [comment]
Thanks for your attention.
This fragment of code is borrowed from [DRIT](https://github.com/HsinYingLee/DRIT). The purpose is to make the output tensor in the range of [0,1]. I have tested the output and it is not precisely in the field of [0,1]. Maybe you need to modify it to be more accurate.
