### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by abhigoku10** [OaDsis/DerainCycleGAN#6]
@OaDsis  hi thanks for sharing the wonderful work , i had few queries 
1. can you please provide the pretrained weights on google drive or one drive 
Thanks in adavance

**Comment by OaDsis** [comment]
Thanks for your attention.
I will upload the pre-trained model and the results in a few days.

**Comment by OaDsis** [comment]
Hello, I have uploaded the pre-training models, please check that.
