### ISSUE TITLE
NameError: name 'load_lua' is not defined

### ISSUE THREAD

**Issue by mawei-north** [OaDsis/DerainCycleGAN#7]
Thanks for your wonderful work. I ran train.py but I meet an error. NameError: name 'load_lua' is not defined. The version of torch is 1.4.0

**Comment by OaDsis** [comment]
Thanks for your attention.
You can download pre-trained vgg16-weight from here: https://drive.google.com/drive/folders/1DvOFGIdXXnNm1iage69HuasUPHZSXYYt.
And put it in "./vgg16/vgg16.weight", you will never face NameError again.

**Comment by mawei-north** [comment]
Okay, thank you very much, I understand it.

**Comment by Mrhard1999** [comment]
为什么下载了文件，依然会出现“NameError: name 'load_lua' is not defined”,load_lua在高版本pytorch中有可以替换的函数吗
