### ISSUE TITLE
What should I do when CUDA out of memory?

### ISSUE THREAD

**Issue by yongjilee** [OaDsis/DerainCycleGAN#8]
I use a 2080TI with 12GB memory to train the model, but it leads to CUDA out of memory. How to solve this problem?

**Comment by OaDsis** [comment]
A GPU with 12GB memory should work for DerainCycleGAN, if not, you can change the '--crop_size' in 'options.py' to a smaller one.

**Comment by yongjilee** [comment]
Can I change the '--resize_size' ? Can it have the same effect?

**Comment by OaDsis** [comment]
Yes, a small level of modification will not obviously change the effect.
