### ISSUE TITLE
gen_xxx.jpg

### ISSUE THREAD

**Issue by hackerax** [OaDsis/DerainCycleGAN#9]
![image](https://user-images.githubusercontent.com/43444280/226090419-9d156ba9-2d7a-4b2f-9a0d-d37511f4d7df.png)
how about gen_xxxxx.jpg   What do these pictures represent

**Comment by OaDsis** [comment]
first row: rain image, derained image, reconstructed rain image;
second row: rain-free image, rain-added image, reconstructed rain-free image;
The second column is not always the same as the first one due to the 'ImagePool' function (refer to CycleGAN).

**Comment by hackerax** [comment]
作者您好&nbsp; 大概跑多少epoch会出效果呢&nbsp; 我现在跑了100epoch 感觉去雨没啥效果呀&nbsp;


shibin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月18日(星期六) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [OaDsis/DerainCycleGAN] gen_xxx.jpg (Issue #9)





 
first row: rain image, derained image, reconstructed rain image;
 second row: rain-free image, rain-added image, reconstructed rain-free image;
 The second column is not always the same as the first one due to the 'ImagePool' function (refer to CycleGAN).

**Comment by OaDsis** [comment]
about 400 epochs
